version: 2

sources:
  - name: olist_dataset
    description: Olist dataset loaded to BigQuery.
    database: dsai-488403
    tables:
      - name: orders
        description: Raw orders data from Olist dataset.
      - name: customers
        description: Raw customers data from Olist dataset.
      - name: order_items
        description: Raw order items data from Olist dataset.
      - name: products_english
        description: Raw products data from Olist dataset.
      - name: sellers
        description: Raw sellers data from Olist dataset.